### ISSUE TITLE
repetitive class name hinder readability and usability

### ISSUE THREAD

**Issue by kefeimo** [tsdat/ingest-template#3]
## Describe the bug
The current template-generated projects share the same class names with tsdat package. (e.g., IngestPipeline, Pipeline)

Significance
- error-prone during import
- hard to read (i.e., need to rely on name space)

## Steps to Reproduce
```
# Follow current workflow in README
...
cookiecutter templates/ingest -o ingest/
...
```

## ~~Expected behavior~~ Best Practice
Include the project name as part of the classname, instead of merely relying on namespace resolve.

## Screenshots

<img width="435" alt="image" src="https://user-images.githubusercontent.com/28743873/162328133-cf889a84-4e0d-416a-adad-4348ce91faea.png">

**Comment by maxwellevin** [comment]
Good find @kefeimo! The name of this class is confusing, I agree. As you said, it also complicates things if you were to try to import multiple different pipelines because they would all have the same name. Using the project name in the classname makes sense to me. 

I'd happily accept a PR for this, otherwise it may be a while before I can get to it myself.

**Comment by kefeimo** [comment]
# Problem description

A bit messy dependency diagram

<img width="353" alt="image" src="https://user-images.githubusercontent.com/28743873/163464283-db520c4e-3454-4012-af59-d23041b7e04e.png">

- The `def run` method have been overriding and being overridden.
- Even Pycharm IDE got confused and claims that `def run` method is overridden by some method in `utils/pipeline.py`, which is not. And the reason is the `class IngestPipeline` in `utils/pipeline.py`is confused with `class IngestPipeline` in `tsdat/pipeline/ingest_pipeline.py` . (No, you don’t see it wrong: both of them have the same class name.) And Pycharm thought the class inherit itself (I thought the same.)
    
     <img width="340" alt="image" src="https://user-images.githubusercontent.com/28743873/163464310-b77e6fe5-6a8d-4746-abaf-33e24d0ac49f.png">
    
- A quick-fix is 
- to rename/refactor the class in utils/pipeline.py. (potentially, IngestPipelineUtil).
    
    result: note that the “Has overridden method” symbol is gone, which is the correct representation
    
    <img width="339" alt="image" src="https://user-images.githubusercontent.com/28743873/163464346-7483354e-41f0-4748-aa61-dd9b068518ae.png">
    
- (Though, a better way to reuse the IngestPipeline and other class is by utilizing composition, instead of inheritance. Which allows a weaker coupling, and improve readability and maintainability.)
    - right now, too many layers of inheritance: (4 layers of inheritance), which is an anti-pattern and against “the zen of Python”: `Flat is better than nested.`
    - override package method is error-prone and hard to maintain.
- After that, rename/refactor class name in custom configured project (e.g., `waves_morro/pipeline/pipeline.py`)
    - Note: I let Pycharm to perform auto refactor for me. The former class name was `Pipeline`, and the new class name is `PipelineUtil`. But in the template, we should utilize more explicit and relevant names, like, `PipelineWavesMorro`)
    - Note: the places cookiecutter template should pay attention to that include class name changes)
        
        <img width="326" alt="image" src="https://user-images.githubusercontent.com/28743873/163464421-5401502c-df43-4700-a74f-80c502373e6a.png">

**Comment by maxwellevin** [comment]
@kefeimo the PR was merged so I'm closing this
